services:
  - type: web
    name: relatim-token-server
    runtime: python
    buildCommand: pip install -r requirements-server.txt
    startCommand: uvicorn token_server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: LIVEKIT_URL
        value: wss://relatim-v1wlyfls.livekit.cloud
      - key: LIVEKIT_API_KEY
        value: APIgNUtuSTugMPF
      - key: LIVEKIT_API_SECRET
        value: G94A3JBc7teQiXnmvA2RO1MTQWRf7FRa7XfWYJCebJAB
    plan: free
    region: singapore
